# Generated by Django 5.2 on 2025-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=2056)),
                ("dt", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="EventModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=64)),
                ("type", models.CharField(max_length=64)),
                ("ts", models.CharField(max_length=32)),
                ("payload", models.CharField(max_length=2056, null=True)),
            ],
        ),
    ]
